import {useEffect, type ReactNode} from 'react';
import styles from './styles.module.css';

function decodeHtmlEntities(input: string): string {
  return input.replaceAll("&quot;", "\"").replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)));
}
// function decodeHtmlEntities(str: string): string {
//   const txt = document.createElement('textarea');
//   txt.innerHTML = str;
//   return txt.value;
// }
const pastebin_data = decodeHtmlEntities(
  `Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_CustomEvent Name=&quot;K2Node_CustomEvent_0&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_CustomEvent&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_CustomEvent_0&#039;&quot;
   CustomFunctionName=&quot;UpdateText&quot;
   NodePosX=-1184
   NodePosY=1088
   NodeGuid=C2A4988C4A33BA50BDB9C3A955D4D1E6
   CustomProperties Pin (PinId=CFB79EB74DCC68E5765640ADA41C2701,PinName=&quot;OutputDelegate&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;delegate&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(MemberParent=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,MemberName=&quot;UpdateText&quot;,MemberGuid=C2A4988C4A33BA50BDB9C3A955D4D1E6),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8A991FCD40A69A8068F19B811E5BDD8F,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_2 C206A779458CB36898D288B5E97E0A74,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_CommutativeAssociativeBinaryOperator Name=&quot;K2Node_CommutativeAssociativeBinaryOperator_1&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_CommutativeAssociativeBinaryOperator&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_CommutativeAssociativeBinaryOperator_1&#039;&quot;
   bIsPureFunc=True
   FunctionReference=(MemberParent=&quot;&#47;Script&#47;CoreUObject.Class&#039;&#47;Script&#47;Engine.KismetStringLibrary&#039;&quot;,MemberName=&quot;Concat_StrStr&quot;)
   NodePosX=288
   NodePosY=1424
   NodeGuid=C30D787040C8D95CD3C1B185625C89CF
   CustomProperties Pin (PinId=2CF62FC24A17322CE28830954090F735,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;CoreUObject.Class&#039;&#47;Script&#47;Engine.KismetStringLibrary&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultObject=&quot;&#47;Script&#47;Engine.Default__KismetStringLibrary&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=236BBCE84B3BB772AA67C0B4FDE18A41,PinName=&quot;A&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableGet_1 0C0B90784B7F447B4B0C5F90295E292C,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BC76FF43409740EC35E6D79502F815A3,PinName=&quot;B&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableGet_3 5D17D788436E2E994B6419BE4EEE209B,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=0011EF0A4F85DDCDE29934812B5C1AAE,PinName=&quot;ReturnValue&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_CallFunction_252 BDCB82324AE0ABAB051F9EA7D39B2439,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_CallFunction Name=&quot;K2Node_CallFunction_252&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_CallFunction&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_CallFunction_252&#039;&quot;
   bIsPureFunc=True
   FunctionReference=(MemberParent=&quot;&#47;Script&#47;CoreUObject.Class&#039;&#47;Script&#47;Engine.KismetTextLibrary&#039;&quot;,MemberName=&quot;Conv_StringToText&quot;)
   NodePosX=576
   NodePosY=1408
   NodeGuid=D7CE4EA8415EB33D361BC990F66F5543
   CustomProperties Pin (PinId=FEF1D00E45F14706840C429FFD10E217,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;CoreUObject.Class&#039;&#47;Script&#47;Engine.KismetTextLibrary&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultObject=&quot;&#47;Script&#47;Engine.Default__KismetTextLibrary&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BDCB82324AE0ABAB051F9EA7D39B2439,PinName=&quot;InString&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_CommutativeAssociativeBinaryOperator_1 0011EF0A4F85DDCDE29934812B5C1AAE,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=EEEC0D414A9ADC50916B78A2C19FE639,PinName=&quot;ReturnValue&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;text&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_2 DECEDA6F41AD65E2C6B4A48A88247E4C,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_SwitchInteger Name=&quot;K2Node_SwitchInteger_2&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_SwitchInteger&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_SwitchInteger_2&#039;&quot;
   NodePosX=-848
   NodePosY=1104
   NodeGuid=DDA7BA40489D205BFDFC18A7B29E63E3
   CustomProperties Pin (PinId=143D0D2E402C6BB69AAC3EB95D54030E,PinName=&quot;Default&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=C206A779458CB36898D288B5E97E0A74,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_CustomEvent_0 8A991FCD40A69A8068F19B811E5BDD8F,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=845852964DCB9665DCAC1CA0632FC840,PinName=&quot;Selection&quot;,PinType.PinCategory=&quot;int&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;0&quot;,AutogeneratedDefaultValue=&quot;0&quot;,LinkedTo=(K2Node_VariableGet_6 7ED798A6439E655CA938EE80F2453071,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A1A10B83466EBBEBAF03E3A30C3D717E,PinName=&quot;NotEqual_IntInt&quot;,PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;CoreUObject.Class&#039;&#47;Script&#47;Engine.KismetMathLibrary&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultObject=&quot;&#47;Script&#47;Engine.Default__KismetMathLibrary&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=True,bDefaultValueIsReadOnly=True,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=C22955D44C6A0FD1870A50BD2468855B,PinName=&quot;0&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_1 D3471AB94E97303B936DCD97B5BC60EC,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=46BAA0A3497458A00574088C794E5A1C,PinName=&quot;1&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_3 B9C05AAB46A21CA1B1826992705421A5,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=D586F8B54D995F6B1BBA209B177484E5,PinName=&quot;2&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_0 D3471AB94E97303B936DCD97B5BC60EC,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_1&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_1&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosX=-608
   NodePosY=992
   NodeGuid=F9E735ED4266A9EA4401FFAF6738874D
   CustomProperties Pin (PinId=D3471AB94E97303B936DCD97B5BC60EC,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_2 C22955D44C6A0FD1870A50BD2468855B,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8920216A4836D898B24A438450C22854,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_9 304FAEAE45F530647568F0A85AC2B977,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DB41872D48AB394528941F8AC15AF633,PinName=&quot;Text&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;Door&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BFF423BF45ED144F23381ABFE9D526D6,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A2E892B04240F10FB68A81A372F71076,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableGet Name=&quot;K2Node_VariableGet_1&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableGet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableGet_1&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosY=1440
   NodeGuid=EC6F9CF44D90AC36868F569DAB95AD4F
   CustomProperties Pin (PinId=0C0B90784B7F447B4B0C5F90295E292C,PinName=&quot;Text&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_CommutativeAssociativeBinaryOperator_1 236BBCE84B3BB772AA67C0B4FDE18A41,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=4ED50A174E8FBBA130BAB9964EB671DE,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_SwitchInteger Name=&quot;K2Node_SwitchInteger_3&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_SwitchInteger&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_SwitchInteger_3&#039;&quot;
   NodePosX=-224
   NodePosY=1136
   NodeGuid=B25CEFF54C578C48BC0038B346F78F70
   CustomProperties Pin (PinId=EC660A9F48DFEB023673C29FE155FB04,PinName=&quot;Default&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=B9C05AAB46A21CA1B1826992705421A5,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_2 46BAA0A3497458A00574088C794E5A1C,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8D3D92BE494EDD9AC1C1AA851A48FA0F,PinName=&quot;Selection&quot;,PinType.PinCategory=&quot;int&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;0&quot;,AutogeneratedDefaultValue=&quot;0&quot;,LinkedTo=(K2Node_VariableGet_7 0ACADBB546904376736E9CB3D9818124,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=C587D6FC41E89B1F6EF9228CB22E6AF7,PinName=&quot;NotEqual_IntInt&quot;,PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;CoreUObject.Class&#039;&#47;Script&#47;Engine.KismetMathLibrary&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultObject=&quot;&#47;Script&#47;Engine.Default__KismetMathLibrary&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=True,bDefaultValueIsReadOnly=True,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=B33D39314A7A32DFB8B72B9498E21B33,PinName=&quot;0&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_3 D3471AB94E97303B936DCD97B5BC60EC,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=1CADF8C741CBC70D92F465A222D5A715,PinName=&quot;1&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_5 D3471AB94E97303B936DCD97B5BC60EC,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BA796BED4628D97EE541C4AD9DF23120,PinName=&quot;2&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_6 D3471AB94E97303B936DCD97B5BC60EC,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=D0EF466C4FDA51F83AEE15885B4D756B,PinName=&quot;3&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_7 D3471AB94E97303B936DCD97B5BC60EC,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_3&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_3&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosX=144
   NodePosY=1024
   NodeGuid=6DC9B1DB43F3AEC283A07D92491E1A54
   CustomProperties Pin (PinId=D3471AB94E97303B936DCD97B5BC60EC,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_3 B33D39314A7A32DFB8B72B9498E21B33,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8920216A4836D898B24A438450C22854,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_10 44162C754A7206F925C40B938254B14B,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DB41872D48AB394528941F8AC15AF633,PinName=&quot;Text&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;Health&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BFF423BF45ED144F23381ABFE9D526D6,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A2E892B04240F10FB68A81A372F71076,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_5&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_5&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosX=144
   NodePosY=1120
   NodeGuid=EE470D0A414520096B960A9AC131E53E
   CustomProperties Pin (PinId=D3471AB94E97303B936DCD97B5BC60EC,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_3 1CADF8C741CBC70D92F465A222D5A715,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8920216A4836D898B24A438450C22854,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_10 44162C754A7206F925C40B938254B14B,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DB41872D48AB394528941F8AC15AF633,PinName=&quot;Text&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;Speed&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BFF423BF45ED144F23381ABFE9D526D6,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A2E892B04240F10FB68A81A372F71076,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_9&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_9&#039;&quot;
   VariableReference=(MemberName=&quot;Text2&quot;,MemberGuid=AFB954584AD9C0DAD98A4082A1F6A0AD,bSelfContext=True)
   NodePosX=-368
   NodePosY=992
   NodeGuid=7B26537845DE4E8A93634C969B97878E
   CustomProperties Pin (PinId=304FAEAE45F530647568F0A85AC2B977,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_1 8920216A4836D898B24A438450C22854,K2Node_VariableSet_0 8920216A4836D898B24A438450C22854,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=736ABDB14FF3C5313D8BA8A3591C50D5,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_Knot_0 1B3A052343BA6C9067FEEC8E0FE1B309,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=17473B664C0FE87A5168F5A8ED3C3600,PinName=&quot;Text2&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot; Bought&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=45A68E4A41531985135F97B4CC19C70D,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=E616AE8643CCDFAF31A3638921951DF6,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableGet Name=&quot;K2Node_VariableGet_3&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableGet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableGet_3&#039;&quot;
   VariableReference=(MemberName=&quot;Text2&quot;,MemberGuid=AFB954584AD9C0DAD98A4082A1F6A0AD,bSelfContext=True)
   NodePosY=1504
   NodeGuid=CD47806747E991CCC6D4B1A9CEE66EA2
   CustomProperties Pin (PinId=5D17D788436E2E994B6419BE4EEE209B,PinName=&quot;Text2&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_CommutativeAssociativeBinaryOperator_1 BC76FF43409740EC35E6D79502F815A3,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=C4FB46F84766B13DCEC8FAA312A2649C,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_6&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_6&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosX=144
   NodePosY=1216
   NodeGuid=D4F642B14F30955E1BAF679AC3D1C5CE
   CustomProperties Pin (PinId=D3471AB94E97303B936DCD97B5BC60EC,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_3 BA796BED4628D97EE541C4AD9DF23120,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8920216A4836D898B24A438450C22854,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_10 44162C754A7206F925C40B938254B14B,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DB41872D48AB394528941F8AC15AF633,PinName=&quot;Text&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;Headshot&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BFF423BF45ED144F23381ABFE9D526D6,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A2E892B04240F10FB68A81A372F71076,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_7&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_7&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosX=144
   NodePosY=1312
   NodeGuid=0D330BAC44980955F663779E8C39B0A3
   CustomProperties Pin (PinId=D3471AB94E97303B936DCD97B5BC60EC,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_3 D0EF466C4FDA51F83AEE15885B4D756B,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8920216A4836D898B24A438450C22854,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_4 304FAEAE45F530647568F0A85AC2B977,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DB41872D48AB394528941F8AC15AF633,PinName=&quot;Text&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;Second Life&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BFF423BF45ED144F23381ABFE9D526D6,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A2E892B04240F10FB68A81A372F71076,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_0&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_0&#039;&quot;
   VariableReference=(MemberName=&quot;Text&quot;,MemberGuid=DFB8D1634BC4DBA7C49D3E87FF8BD4B3,bSelfContext=True)
   NodePosX=-576
   NodePosY=1216
   NodeGuid=F2F9354F422E9B07E77192BE10D2E074
   CustomProperties Pin (PinId=D3471AB94E97303B936DCD97B5BC60EC,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_SwitchInteger_2 D586F8B54D995F6B1BBA209B177484E5,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=8920216A4836D898B24A438450C22854,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_9 304FAEAE45F530647568F0A85AC2B977,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DB41872D48AB394528941F8AC15AF633,PinName=&quot;Text&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;Projectile&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=BFF423BF45ED144F23381ABFE9D526D6,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A2E892B04240F10FB68A81A372F71076,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_4&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_4&#039;&quot;
   VariableReference=(MemberName=&quot;Text2&quot;,MemberGuid=AFB954584AD9C0DAD98A4082A1F6A0AD,bSelfContext=True)
   NodePosX=384
   NodePosY=1312
   NodeGuid=62F7F5A9436CC4E7CB9C6E9D440C73AF
   CustomProperties Pin (PinId=304FAEAE45F530647568F0A85AC2B977,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_7 8920216A4836D898B24A438450C22854,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=736ABDB14FF3C5313D8BA8A3591C50D5,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_Knot_1 3CEEFE734D5DD293D6C0858DA298A702,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=17473B664C0FE87A5168F5A8ED3C3600,PinName=&quot;Text2&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot; Bought&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=45A68E4A41531985135F97B4CC19C70D,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=E616AE8643CCDFAF31A3638921951DF6,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_10&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_10&#039;&quot;
   VariableReference=(MemberName=&quot;Text2&quot;,MemberGuid=AFB954584AD9C0DAD98A4082A1F6A0AD,bSelfContext=True)
   NodePosX=432
   NodePosY=1120
   NodeGuid=2D3DADF346D81187C03E9BBFB109FF49
   CustomProperties Pin (PinId=44162C754A7206F925C40B938254B14B,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_6 8920216A4836D898B24A438450C22854,K2Node_VariableSet_5 8920216A4836D898B24A438450C22854,K2Node_VariableSet_3 8920216A4836D898B24A438450C22854,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=CCFA450C4413DD4E0164E4AA9EB7CD88,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_Knot_1 3CEEFE734D5DD293D6C0858DA298A702,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=944A887042398B4130AE82AA8AF2A393,PinName=&quot;Text2&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot; Upgraded&quot;,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=5D9EF01A4C06345F0C8430999325FBD2,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;string&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=01AD53024C34A501BCF4EE8A3645CB20,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableGet Name=&quot;K2Node_VariableGet_6&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableGet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableGet_6&#039;&quot;
   VariableReference=(MemberName=&quot;InteractionType&quot;,MemberGuid=A697C6F448D8D24FEE0CE08884455128,bSelfContext=True)
   NodePosX=-1120
   NodePosY=1248
   NodeGuid=589FCCF94BCB348254478A9C22A5647A
   CustomProperties Pin (PinId=7ED798A6439E655CA938EE80F2453071,PinName=&quot;InteractionType&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;int&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;0&quot;,AutogeneratedDefaultValue=&quot;0&quot;,LinkedTo=(K2Node_SwitchInteger_2 845852964DCB9665DCAC1CA0632FC840,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=7E28677442BF85422DB244A247497E6D,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableGet Name=&quot;K2Node_VariableGet_7&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableGet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableGet_7&#039;&quot;
   VariableReference=(MemberName=&quot;PerkType&quot;,MemberGuid=F06CD56745974AD465BB239B3F2A59B2,bSelfContext=True)
   NodePosX=-512
   NodePosY=1376
   NodeGuid=E6A8233D485EF8DB7F2F67B10C79B701
   CustomProperties Pin (PinId=0ACADBB546904376736E9CB3D9818124,PinName=&quot;PerkType&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;int&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue=&quot;0&quot;,AutogeneratedDefaultValue=&quot;0&quot;,LinkedTo=(K2Node_SwitchInteger_3 8D3D92BE494EDD9AC1C1AA851A48FA0F,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=F98DF3F1411F5309AFC6C49C6490612C,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_VariableSet Name=&quot;K2Node_VariableSet_2&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_VariableSet&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_VariableSet_2&#039;&quot;
   VariableReference=(MemberName=&quot;UpgradeText&quot;,MemberGuid=FFAE12D94CD238A9698108A03565C882,bSelfContext=True)
   NodePosX=912
   NodePosY=1168
   NodeGuid=B48DB2704DE4922D62B68792E7AB9794
   CustomProperties Pin (PinId=629BC31F43C3023916A41C849384F615,PinName=&quot;execute&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_Knot_1 E0BEBE6E431CD2C70E1DBAB19129C437,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=CFEDEB434734981AC8AC8085D7437EE4,PinName=&quot;then&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=DECEDA6F41AD65E2C6B4A48A88247E4C,PinName=&quot;UpgradeText&quot;,PinType.PinCategory=&quot;text&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_CallFunction_252 EEEC0D414A9ADC50916B78A2C19FE639,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=9B14B08B4E161398B2E61E976C9B6A84,PinName=&quot;Output_Get&quot;,PinToolTip=&quot;Retrieves the value of the variable, can use instead of a separate Get node&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;text&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=524BA01E465DBBA4C2DCA1ABF2DF1ABA,PinName=&quot;self&quot;,PinFriendlyName=NSLOCTEXT(&quot;K2Node&quot;, &quot;Target&quot;, &quot;Target&quot;),PinType.PinCategory=&quot;object&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=&quot;&#47;Script&#47;UMG.WidgetBlueprintGeneratedClass&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded_C&#039;&quot;,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=True,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_Knot Name=&quot;K2Node_Knot_0&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_Knot&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_Knot_0&#039;&quot;
   NodePosX=672
   NodePosY=1008
   NodeGuid=247479DA4DCA3C29853A219915112635
   CustomProperties Pin (PinId=1B3A052343BA6C9067FEEC8E0FE1B309,PinName=&quot;InputPin&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_9 736ABDB14FF3C5313D8BA8A3591C50D5,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=True,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=49607062406952F2D26C1F8EB81594E8,PinName=&quot;OutputPin&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_Knot_1 3CEEFE734D5DD293D6C0858DA298A702,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
Begin Object Class=&#47;Script&#47;BlueprintGraph.K2Node_Knot Name=&quot;K2Node_Knot_1&quot; ExportPath=&quot;&#47;Script&#47;BlueprintGraph.K2Node_Knot&#039;&#47;Game&#47;Ui&#47;BoughtItem&#47;HealthUpgraded.HealthUpgraded:EventGraph.K2Node_Knot_1&#039;&quot;
   NodePosX=816
   NodePosY=1184
   NodeGuid=6E5102694A3C05EAF85DC4AE4270041C
   CustomProperties Pin (PinId=3CEEFE734D5DD293D6C0858DA298A702,PinName=&quot;InputPin&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_10 CCFA450C4413DD4E0164E4AA9EB7CD88,K2Node_Knot_0 49607062406952F2D26C1F8EB81594E8,K2Node_VariableSet_4 736ABDB14FF3C5313D8BA8A3591C50D5,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=True,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=E0BEBE6E431CD2C70E1DBAB19129C437,PinName=&quot;OutputPin&quot;,Direction=&quot;EGPD_Output&quot;,PinType.PinCategory=&quot;exec&quot;,PinType.PinSubCategory=&quot;&quot;,PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(K2Node_VariableSet_2 629BC31F43C3023916A41C849384F615,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object`);

console.log(pastebin_data);

let x = false;
export default function Blueprint(): ReactNode {
  useEffect(() => {
    if (x) return;
    x = true;
      new (window as any).blueprintUE.render.Main(
        pastebin_data,
        document.getElementsByClassName('playground')[0],
        {height:"643px"}
    ).start();
  }, []);

  return (
    <section className={styles.features}>
      <div className="container">
        <div className="row playground">
          <h1>TEST</h1>
        </div>
      </div>
    </section>
  );
}
